---
title: "Data Science for Economists"
# subtitle: "<html><div style='float:left'></div><hr color='#EB811B' size=1px width=796px></html>"
subtitle: "API Presentation"
author: "Nathan Bracken"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true 
      highlightSpans: true
      countIncrementalSlides: false
      keep_md: true
---
## Problem!
  - Computers cannot easily use information that humans create on the web
  - Reading, Copying, and pasting thousands of data entries takes a long time
  - Lets get the "stupid" computer to understand inconsistent, "stupid" humans
---

## What is an API?
  - Picture from zapier
  - Client (Us): A program exchanges data with a server through an API 
  - API -> Application Programming Interface (stores computer digestible data)
  - Server: A powerful computer that hosts the API and Web Information
  - Key: This helps the computer read the data we see on a website
   
---

## Ok cool. How does this communication work?
  - Protocol: The "etiquette" underlying how computers communicate (e.g. HTTP).
  - Requests: What the client asks of the server
  - Make a request following the Protocol
  - This follows the request response cycle
---

## How do I make a request?
 - Requests conatain 4 things: 
    - URL 
    - Methods
    - List of Headers 
    - Body
---

## URL?
 - URL is an address on the internet for a thing that an API expands upon
  - Uniform Resource Locator
  - Key: The API "creates" URLs for more resources we see on the web

---
## Method? Similar to shell commands!
 - Methods: The "verbs" that clients use to talk with a server. 
  - Common Methods:
    - GET -> (i.e. ask a server to retrieve information) 
    - POST -> Ask for the creation of a new resource
    - PUT -> Edit or update existing resource
    - DELETE -> Delete a resource
 - Think of this as a data delivery
---

## Headers
  - The background (meta) information about the request
  - Time request was made
  - Size of the request body
  - Credentials - (we will get to this later)
  
## Body
  - The data the client wants to send to the server
  - Request details

---

## Great! We made our request!
  - We should get a "response"
  - Response: The server's response. 
  - This includes: 
    - a Status Code (e.g. "404" if not found, or "200" if successful)
    - a Header (i.e. meta-information about the reponse)
    - a Body (i.e the actual content that we're interested in).

---

## How do we receive the information? con associative array
  - A data representation method
  - The server creates a format easy for both machines to understand
  - JSON -> Javascript Object Notation -> Keys and Values
  '''{r}
  
  '''
  - XML -> Extensible Markup Language -> Nodes
  '''{r}
  '''
  - We can specify a specific format in our header to send/receive
    - Application -> Receiving
    - Accept -> Sending
    
---

## It can't be that simple.
  - It seems like we suddenly have free reign over all information! Just Request!
  - Unfortunately it is not that simple
  - Servers need to authenticate just like logging into anything
  - Types of authentication: 
    - Basic Auth
    - API Key Auth
    - OAuth -> Open Authorization -> Automates Key Exchange
    
---

##API Design
  - Two most commonly used formats are: 
    - SOAP -> XML based that standardizes structures for requests and responses
    - REST -> Representational State Transfer -> Most common (much user choice)
  -Select a format and: 
    - Choose the resources that should be used ->
    - Assign resources to a url -> creating an endpoint for the API
    - Create a level of permissions for allowable actions on resources
    - Figure out what pieces of data are required for each action
    
---

##Why are APIs Important? 
  - They integrate systems together -> Like working with github
  - Types of Integration
    - Client Driven -> Using an app on your phone to do something
    - Server Driven -> Using Polling to measure and send information to client
      - Polling -> Asking for repeated updates
      - Long Polling -> Increased efficiency, updates after something happens
    - Polling can have some drawbacks -> Too many requests will overload server
    - Webhooks -> Lets the client act as a server and wait for requests
    
---

## Ok great Nathan, we can request and receive data. What now? 
  - Look for common documentation
  - Use an HTTP Client
  - Write our own code in a language specified in the API library
  - Best to use a computer that can act as a server -> Webhook
  
---

## Resources

Zapier Book:
https://zapier.com/learn/apis/

Subscription webhooks link:
https://github.com/pubsubhubbub/

REST Hooks:
http://resthooks.org/docs/

---